/*
 * This file contains the nodes of the second section (ID) of the simulator,
 * adapted to shift horizontally depending on the active simulator mode.
 */

import { useSimulator } from "@/context/shared/SimulatorContext";
import { Node } from "@xyflow/react";

export const useIDNodes = (): Node[] => {
  const { typeSimulator } = useSimulator();

  // Si es modo "pipeline", desplazamos todo ID hacia la derecha (ej. porque IF es más ancho)
  const offsetX = typeSimulator === "pipeline" ? 300 : 0;

  return [
    {
      id: "ID",
      type: "group",
      data: { label: "Section 2" },
      position: { x: 870 + offsetX, y: 0 },
      draggable: false,
      zIndex: 0,
      style: {
        width: 740,
        height: 1330,
        backgroundColor: "#FFF9C4",
        border: "1px solid #FFF9C4",
        borderRadius: 8,
      },
    },
    {
      id: "title-ID",
      type: "title",
      data: { label: "Decode (ID)" },
      position: { x: 0, y: 0 },
      parentId: "ID",
      extent: "parent",
      draggable: false,
      style: {
        width: 740,
        height: 50,
        backgroundColor: "transparent",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },
    {
      id: "ruWr",
      type: "ruWr",
      data: { label: "RUWR" },
      position: { x: 120, y: 814 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 90,
        height: 30,
        backgroundColor: "transparent",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },
    {
      id: "registersUnit",
      type: "registerUnit",
      data: { label: "Registers Unit" },
      position: { x: 255, y: 435 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 360,
        height: 450,
        backgroundColor: "transparent",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },
    {
      id: "immSrc",
      type: "immSrc",
      data: { label: "IMMSrc" },
      position: { x: 145, y: 1028.5 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 90,
        height: 30,
        backgroundColor: "transparent",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },
    {
      id: "immGenerator",
      type: "immGenerator",
      data: { label: "Immediate Generator" },
      position: { x: 285, y: 935.5 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 330,
        height: 150,
        backgroundColor: "transparent",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    // 🔽 Puedes pegar aquí el resto de los nodos y pivotes igual que antes
    // Solo recuerda que no necesitas modificar sus posiciones internas
    // ya que su `parentId` es "ID", y ese grupo ya está desplazado por `offsetX`

    // Por ejemplo:
    {
      id: "pivot2",
      type: "pivot2",
      data: { label: "" },
      position: { x: 680, y: 822.3 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },
    {
      id: "pivot3",
      type: "pivot3",
      data: { label: "" },
      position: { x: 50, y: 843 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },
    {
      id: "pivot5",
      type: "pivot5",
      data: { label: "" },
      position: { x: 680, y: 1077 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "red",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot12",
      type: "pivot12",
      data: { label: "" },
      position: { x: 100, y: 1131 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot18",
      type: "pivot18",
      data: { label: "" },
      position: { x: 50, y: 254 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot19",
      type: "pivot19",
      data: { label: "" },
      position: { x: 50, y: 128 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot20",
      type: "pivot20",
      data: { label: "" },
      position: { x: 50, y: 563 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot21",
      type: "pivot21",
      data: { label: "" },
      position: { x: 50, y: 483 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot22",
      type: "pivot22",
      data: { label: "" },
      position: { x: 50, y: 643 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot26",
      type: "pivot26",
      data: { label: "" },
      position: { x: 50, y: 976.5 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },
    {
      id: "pivot27",
      type: "pivot27",
      data: { label: "" },
      position: { x: 50, y: 1169 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },
    {
      id: "pivot28",
      type: "pivot28",
      data: { label: "" },
      position: { x: 100, y: 1169 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },
    {
      id: "pivot29",
      type: "pivot29",
      data: { label: "" },
      position: { x: 100, y: 1210 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot30",
      type: "pivot30",
      data: { label: "" },
      position: { x: 270, y: 1169 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot31",
      type: "pivot31",
      data: { label: "" },
      position: { x: 270, y: 1210 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot32",
      type: "pivot32",
      data: { label: "" },
      position: { x: 450, y: 1169 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivot33",
      type: "pivot33",
      data: { label: "" },
      position: { x: 450, y: 1210 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 5,
        height: 5,
        backgroundColor: "black",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivotJump1",
      type: "pivotJump1",
      data: { label: "pivotJump1" },
      position: { x: 84, y: 953.4 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 47,
        height: 47,
        backgroundColor: "transparent",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivotJump2",
      type: "pivotJump2",
      data: { label: "pivotJump2" },
      position: { x: 664, y: 363 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 47,
        height: 47,
        backgroundColor: "transparent",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivotJump4",
      type: "pivotJump4",
      data: { label: "pivotJump4" },
      position: { x: 664, y: 688 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 47,
        height: 47,
        backgroundColor: "transparent",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivotJump5",
      type: "pivotJump5",
      data: { label: "pivotJump5" },
      position: { x: 664, y: 985 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 47,
        height: 47,
        backgroundColor: "transparent",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },

    {
      id: "pivotJump10",
      type: "pivotJump10",
      data: { label: "pivotJump10" },
      position: { x: 34, y: 155 },
      parentId: "ID",
      extent: "parent",
      style: {
        width: 47,
        height: 47,
        backgroundColor: "transparent",
        border: "none",
        borderRadius: 0,
        padding: 0,
        boxShadow: "none",
      },
    },
  ];
};
