import {
  commands,
  ConfigurationChangeEvent,
  ExtensionContext,
  TextDocumentChangeEvent,
  TextEditor,
  TextEditorSelectionChangeEvent,
  Uri,
  window,
  workspace,
  ThemeColor,
  StatusBarItem,
} from 'vscode';

import { SimulatorPanel } from './panels/SimulatorPanel';
import { DataMemPanelView } from './panels/DataMemPanel';
import { RVContext, RVExtensionContext } from './support/context';
import { encodeIR, ProgramMemoryProvider } from './progmemview/progmemprovider';

export async function activate(context: ExtensionContext) {
  console.log('Activating extension RiscV');
  const startTime = Date.now();

  const rvContext = RVContext.create(context);
  /*
    rvContext.lineTracker.onDidChangeActiveLines(async () => {
      console.log('LineTracker: line changed ', rvContext.lineTracker.currentLine);
      if (window.activeTextEditor) {
        annotateSourceLines(window.activeTextEditor);
      }
    });
  */

  // const programMemoryProvider = new ProgramMemoryProvider(rvContext);
  // context.subscriptions.push(
  //   workspace.registerTextDocumentContentProvider(
  //     ProgramMemoryProvider.scheme,
  //     programMemoryProvider
  //   )
  // );

  // const binaryEncodingProvider = new BinaryEncodingProvider(rvContext);
  // binaryEncodingProvider.registerHoverProviders();



  const activationTime = Date.now() - startTime;
  console.log(`%cExtension initialization finished. Took ${activationTime / 1000} secs.`, "color: blue;");
}

export function deactivate() {
  console.log('Deactivating extension');
}


/**
 * Report the result of the program's parsing.
 * @param statusBarItem where the error is reported
 * @param status whether the parsing was successful ("Passed") or it resulted in
 * an error ("Failure")
 */
function reportBuildStatus(
  statusBarItem: StatusBarItem,
  status: 'Passed' | 'Failure'
) {
  if (status === 'Passed') {
    statusBarItem.text = 'RISCV: success build';
    statusBarItem.backgroundColor = new ThemeColor('statusBar.background');
    statusBarItem.show();
  } else {
    statusBarItem.text = 'RISCV: error';
    statusBarItem.backgroundColor = new ThemeColor(
      'statusBarItem.errorBackground'
    );
    statusBarItem.show();
  }
}

function simulateProgram(
  editor: TextEditor | undefined,
  extensionUri: Uri,
  rvContext: RVExtensionContext
) {
  if (editor) {
    const document = editor.document;
    rvContext.setSourceDocument(document);
    if (!rvContext.validIR()) {
      window.showErrorMessage('Build process failed. Cannot simulate program');
      return;
    }
    const simulator = SimulatorPanel.getPanel(extensionUri);
    if (simulator) {
      window.showInformationMessage('Starting simulation');
      rvContext.startSimulation(
        simulator,
        DataMemPanelView.render(extensionUri, {}),
        RegisterPanelView.render(extensionUri, {}),
        {
          sort: workspace
            .getConfiguration()
            .get('rv-simulator.registersView.sort'),
          initialSp: workspace
            .getConfiguration()
            .get(
              'rv-simulator.dataMemoryView.stackPointerInitialAddress'
            ) as number
        }
      );
    }
  }
}

function exportProgMemJSON(extensionUri: Uri, rvContext: RVExtensionContext) {
  const program = rvContext.exportJSON();
  workspace
    .openTextDocument({ language: 'json', content: program })
    .then((document) => {
      window.showTextDocument(document).then((editor) => {
        commands.executeCommand('editor.action.formatDocument');
      });
    });
}

/**
 * Exports the internal representation generated by the parser to a document and opens it.
 * @param extensionUri uri of the extension
 * @param rvContext extension context
 */
function exportIRJSON(extensionUri: Uri, rvContext: RVExtensionContext) {
  const ir = rvContext.getIR();
  const irString = JSON.stringify(ir);
  if (ir !== undefined) {
    workspace.openTextDocument({ language: 'json', content: irString });
  }
}